version: "3.8"

services:
  si-card-bot:
    image: ${IMAGE_URI}
    env_file:
      - .env
    expose:
      - "3000" # internal only, not public
    restart: unless-stopped
    networks:
      - monitor-net

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - "3001:3001" # public UI
    volumes:
      - ./uptime-kuma:/app/data
    restart: unless-stopped
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
